### ISSUE TITLE
Export content of wikilinks into the PDF

### ISSUE THREAD

**Issue by khofstadter** [Hegghammer/foam-templates#1]
Hello, 

I managed to export the Markdown file into a PDF. 

```

## 1. Introduction
[[introduction]]

## 2. Literature Review
[[litrev]]

## 3. Theoretical Framework
[[theoretical-framework]]

## 4. Experimental Study
[[1-model]]
[[2-design]]
[[3-shot-selection]]
[[4-pilot]]
[[5-data-collection]]
[[6-analysis]]

## 5. Conclusion
[[conclusion]]
```

The PDF looks like this: 

![screenshot_ 2024-12-17 at 14 38 14](https://github.com/user-attachments/assets/821c1b89-3dbc-4f88-b2ab-158d61e0a102)

Is it possible with your code to export the content of the wikilinks into the PDF as well? 

Thank you!

k

**Comment by Hegghammer** [comment]
Good question. I don't think it is currently possible, unfortunately. The [notes in notes](https://foambubble.github.io/foam/user/features/including-notes.html) functionality only works for Markdown preview in VSCode.

However, you can do something close to it on the command line. Pandoc lets you combine several `.md` files into one pdf, like so: `pandoc file1.md file2.md -o combined.pdf`. To use the template, you would write: 

```
pandoc note1.md note2.md -o combined.pdf --from=markdown+wikilinks_title_after_pipe --resource-path $WORKSPACE/.pandoc --template foam --listings
```
